### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by alexbagirov** [MoarCatz/chat-client#24]
From now we are going to serve each request using [WebSockets](https://ru.wikipedia.org/wiki/WebSocket) and [Tornado](http://www.tornadoweb.org/en/stable/).

Those are some steps for us in order to proceed with it:
- [x] Carefully remove old code :fire: 
- [x] Add the `IOLoop`
- [x] Add the connection process and requests sending/receiving :electric_plug:

This is going to be fascinating :sparkles:
